name: CI/CD Pipeline

on:
  push:
    branches: ["main"]   # chỉ chạy khi có push vào nhánh main

jobs:
  build:
    runs-on: ubuntu-latest   # máy ảo Linux mới nhất

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # lấy code trong repo về

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2   # chuẩn bị Docker buildx để build multi-platform

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # lấy từ GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}   # lấy từ GitHub Secrets

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .   # build từ thư mục gốc
          push: true   # push image lên DockerHub
          tags: mrkai03/ci-cd-demo:latest   # tên image + tag
